name: Build API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/build-api.yml'
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/build-api.yml'

permissions:
  contents: read

defaults:
  run:
    working-directory: api

jobs:
  build:
    name: Java Dragonwell 21 Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: dragonwell
          java-version: '21'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-jar
          path: api/build/libs/*.jar
          if-no-files-found: error
